# .github/workflows/lint.yml

name: Lint

on:
  pull_request:
  push:
    branches: [master]

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node
        with:
          node-version: 18

      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          only_changed: true
          same_commit: true
          prettier_options: --write frontend/src